#5. Sprint 11
Saeldrit/java-filmorate pull request #1
Opened 2023-03-12 11:37 UTC by Saeldrit

2023-03-12 17:29 UTC, Donald522 requested changes
Привет!
В целом все норм, получение сущностей из БД сделано одним запросом, хорошо.

Создать все таблицы можно в одном файлике :)

2023-03-12 17:29 UTC, Donald522 commented on src/main/resources/db/migration/V4__Create_table_users.sql
> +    login    VARCHAR(255) NOT NULL,
Но логин можно сделать unique constraint / unique index

2023-03-12 17:29 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/enumeration/for_users/FriendsInteractionEnum.java
> +    IS_NIT_FRIEND("Не друзья");
nit?

2023-03-12 17:29 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/enumeration/for_users/FriendsInteractionEnum.java
> +    IS_FRIEND("Друзья"),
А в чем смысл такого title?
И так же понятно)

2023-03-12 17:29 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/db_h2/FilmRepositoryDB.java
> +	public FilmRepositoryDB(@Qualifier("filmQuery") SqlQuery sqlQuery,
Можно название поля сделать filmQuery и обойтись без клифаер и конструктора

2023-03-12 17:29 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/db_h2/FilmRepositoryDB.java
> +		Film film = findById(id);
А зачем select делать перед удалением?
Чтобы потом return сделать?

Не уверен про h2, может она так и не умеет, но postgres умеет возвращать удаленную строку командой returning

2023-03-12 17:29 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/InteractionServiceWithFilmLibrary.java
> +		userRepository.like(filmId, userId);
А в чем смысл делать какие-то in-memory изменения в User?
Если у нас приложение перезапустится, то эта информация пропадет, насколько я понимаю.

2023-03-12 17:29 UTC, Donald522 commented on src/main/resources/db/migration/V3__Create_table_films.sql
> +    rate         INTEGER DEFAULT 0,
А зачем эта колонка, если для построения рейтинга ты все равно делаешь join film_likes таблицы и группируешь ее?

2023-03-12 17:29 UTC, Donald522 commented on src/main/resources/application-user.yml
> +  drop-table: "DROP TABLE users"
Вот такое в продакшн код лучше никогда не помещать
Это как с ружьем, которое висит на стене.

2023-03-12 17:29 UTC, Donald522 commented on src/main/resources/application-film.yml
> +  drop-table: "DROP TABLE films"
И это тоже

2023-03-12 17:29 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/enumeration/for_films/MPAEnum.java
> +public enum MPAEnum {
Не увидел как используется этот класс

2023-03-18 15:46 UTC, Saeldrit commented on src/main/resources/db/migration/V4__Create_table_users.sql
> +    login    VARCHAR(255) NOT NULL,
Доработал

2023-03-18 15:47 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/model/enumeration/for_users/FriendsInteractionEnum.java
> +    IS_NIT_FRIEND("Не друзья");
Не, не nit)

2023-03-18 15:47 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/repository/db_h2/FilmRepositoryDB.java
> +	public FilmRepositoryDB(@Qualifier("filmQuery") SqlQuery sqlQuery,
Выполнено)

2023-03-18 15:48 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/repository/db_h2/FilmRepositoryDB.java
> +		Film film = findById(id);
Вот да, h2 так не умеет)

2023-03-18 15:49 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/service/InteractionServiceWithFilmLibrary.java
> +		userRepository.like(filmId, userId);
В пачке написал

2023-03-19 17:01 UTC, Donald522 approved these changes
Привет!

Все хорошо, принимается

2023-04-05 04:20 UTC, merged