#1: sprint 1
Saeldrit/java-filmorate pull request #2
Opened 2022-12-19 06:22 UTC by Saeldrit

2022-12-22 18:45 UTC, Donald522 requested changes
Привет!
На вопросы вроде постарался ответить, замечания написал.
Еще из общих рекомендаций - добавить какие-нибудь логи. А то сервис совсем никак не сообщает о своей работе никуда.

2022-12-22 18:45 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
А где же тесты?
Советую сразу писать скелет и для тестов контроллеров, потом, по мере добавления функционала, это будет сделать сложнее.

Какое-то апи уже есть, на него вполне можно написать тесты

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (Exception e) {
А почему не ExptionHandler?
Код будет намного чище

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity<>(film, HttpStatus.NOT_FOUND);
Почему при ошибке на создании возвращается 500, а здесь 404?

Коды ответов это важная часть апи.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +     * Заворачивать его в ResponseEntity, или просто вернуть сущность?
ResponseEntity точно нужен, тк он несет в себе http код ответа.
Возвращать сущность - хорошая идея. Иначе как вызывающий код узнает под каким id создалась сущность?

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +     * Или это приемлемая работа для контроллера?
Написал в FilmController как раз.
Это приемлемо с той точки зрения, что будет работать. Но так никто не пишет давно.

Есть механизм ExceptionHandler. Там нужны аннотации ControllerAdvice, ExceptionHandler. Странно, что этого не было в теории. Но в интернете много инфы об этом, вот например
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

Это удобно в том плане, что у тебя много методов могут кидать одни и те же исключения, и иначе тебе пришлось бы написать много одинаковых catch блоков.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@EqualsAndHashCode(exclude = {"description", "duration"})
Есть аннотации Data, Value, которые заменяют всю эту портянку из аннотаций.
Я больше люблю Value, она не генерит сеттеры. Я не люблю сеттеры)
Вместо этого использую аннотацию With

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/annotation/DateValidator.java
> + * но как мне достать переданное значение тут не понимаю.
Пробовал так?
http://dolszewski.com/java/custom-parametrized-validation-annotation/

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/AbstractCRUDRepository.java
> +    public List<O> backAllValues() {
Почему List?
Если ты хочешь иметь generic интерфейс, то не стоит так сильно ограничивать его. Верни Collection или Iterable.

List - это коллекция со спецификой. Когда в интерфейсе указывают List - явно дают понять, что важен порядок. Здесь порядок не важен.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/AbstractCRUDRepository.java
> +public abstract class AbstractCRUDRepository<I, O> implements InterfaceCRUD<I, O> {
А что значит I в типе?
O - это видимо object.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/AbstractCRUDRepository.java
> +public abstract class AbstractCRUDRepository<I, O> implements InterfaceCRUD<I, O> {
Абстрактный класс это пережиток прошлого.
Сделай лучше интерфейс с дефолтной реализацией некоторых методов, если надо.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +            while (true) {
Такой алгоритм будет плохо работать под нагрузкой, убивая производительность своей линейной сложностью от объема данных. 
Лучше сделай просто инкремент. То, что будут пропуски в id - это нормально, так работают все sequence генераторы в базах.
В данном случае производительность важнее, чем отсутствие пропусков в id.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +        getObjectMap().put(film.getId(), film);
А если id проставлен и существует уже в хранилище, то мы его перетрем? Не хорошо как-то.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +        intermediateId = film.getId();
В этом мало смысла, если честно. 
Мы, конечно, еще не проходили многопоточку, но это это точно не будет работать в многопоточной среде. Лучше не усложнять так с id.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +            throw new ValidationException("id not found");
Лучше сделать отдельное исключение для этого, назвать его EntityNotFoundException.

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserRepository.java
> + * Не могу понять, как мне лучше вынети в абстрактный класс generateId?
Дубликация кода не лечится абстрактными классами.
Дубликация кода лечится композицией классов.
Просто сделай класс IdGenerator. Он может быть общим для фильмов и пользователей (тогда id не будут между ними пересекаться, а можно сделать 2 его инстанса. Можно сделать интерфейс idGenerator с 2 реализациями под фильмы и пользователей . Дело вкуса)

2022-12-22 18:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return repository.find(id);
Если например сущность не найдена, то хорошо бы вернуть наружу 404 код. 
Можно 2 варианта сделать:
либо тут вернуть null и проверить в контроллере
либо тут бросить исключение и добавить обработчик этого исключения, чтобы на это исключение всегда возвращался код 404

Второй вариант предпочтительнее.

2022-12-23 08:27 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +        getObjectMap().put(film.getId(), film);
изменил метод put() на putIfAbsent().

2023-01-04 13:13 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (Exception e) {
Добавил ExceptionHandler

2023-01-05 20:00 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Component
Тоже самое, эта аннотация тут не нужна

2023-01-05 20:05 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +            return Film.builder()
У ломбока есть аннотация With
Можно было бы написать `return film.withId(generateId())`

2023-01-05 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film filmAfterRemoving = repository.delete(id);
При удалении тоже хорошо бы вернуть 404, если сущность не найдена

2023-01-05 20:07 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Return film by id \"{}\"", id);
Можно использовать одинарные кавычки, их вроде не надо экранировать)

2023-01-06 09:45 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> + * Насколько важно указывать у моделей @Component? Ведь спринг вроде сам понимает, что это бин?
Спасибо. Я сделаю заметку на этот счёт. Я действительно считал, что модель тоже является бином и лекции по курсу меня запутали.

2023-01-06 09:45 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Getter
Исправил на Value и With

2023-01-06 09:45 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film filmAfterRemoving = repository.delete(id);
Хорошо. Исправил.

2023-01-06 20:10 UTC, Donald522 approved these changes
Привет!
Сейчас все хорошо.

2023-01-06 20:10 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserRepository.java
> +     * @With создает конструктор под капотом и если объект равен
Внутри with нет никаких условий. Это как setter, только возвращает новый объект, который является полной копией за исключением одного поля.
Не важно, что сейчас установлено в этом поле, null или нет, вызов with всегда перезапишет это значение переданным.
Так что это не костыль, а правильное решение.

2023-01-07 07:35 UTC, merged